secrets:
  config_json:
    file: secrets.json

services:
  foundry:
    image: felddy/foundryvtt:11.315
    hostname: my_foundry_host
    restart: always
    volumes:
      - type: bind
        source: /home/justask/node/foundaryvtt/data
        target: /data
    environment:
      - FOUNDRY_HOSTNAME=null
      - FOUNDRY_IP_DISCOVERY=true
      - FOUNDRY_COMPRESS_WEBSOCKET=true
      - FOUNDRY_LANGUAGE=ru.core
      - FOUNDRY_ROUTE_PREFIX=fiopteris
      - FOUNDRY_CSS_THEME=foundry
      - FOUNDRY_MINIFY_STATIC_FILES=true
      - TIMEZONE=RU
    ports:
      - target: 30000
        published: 30000
        protocol: tcp
    secrets:
      - source: config_json
        target: config.json

